name: Deploy Next.js Static Site

on:
  push:
    branches:
      - main  # Change this if you're using a different branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Required for deploying to GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}"
          echo "NEXT_PUBLIC_FLOWISE_API_KEY=${{ secrets.NEXT_PUBLIC_FLOWISE_API_KEY }}"
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_FLOWISE_API_KEY: ${{ secrets.NEXT_PUBLIC_FLOWISE_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages  # Ensure you're deploying to the correct branch
